name: Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Image Name
        run: |
          IMAGE_NAME="davidzz/ca-wildfire:${GITHUB_SHA:0:7}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
      - name: Build Image
        run: |
          docker build --rm --force-rm -t "${IMAGE_NAME}" .
          echo -n "Built image size: "
          docker images "${IMAGE_NAME}" --format "{{.Size}}"
      # - name: Login to Dockerhub
      #   run: >
      #     echo '${{secrets.DOCKERHUB_PASSWORD}}' | docker login
      #     -u '${{secrets.DOCKERHUB_USERNAME}}' --password-stdin
      # - name: Push to Dockerhub
      #   run: docker push "${IMAGE_NAME}"
